grammyjs/grammY

.all-contributorsrc
CONTRIBUTING.md
README.md
deno/README.md
deno/src/bot.ts
deno/src/composer.ts
deno/src/context.ts
deno/src/convenience/session.ts
deno/src/convenience/webhook.ts
deno/src/core/client.ts
deno/src/filter.ts
node-backport/README.md
node-backport/package.json

Dedicated docs in the README for contributors.
Also begins following the specs of [allcontributors.com](https://allcontributors.com), and updates the URL in the JSDoc comments to point to [grammy.dev](https://grammy.dev)  instead of the old preview domain.

Write contribution guide

---

deno/src/core/payload.ts
deno/src/platform.ts
node-backport/platform.ts

… by hiding the `file` property behind a symbol that is only exported internally.
This makes it much harder to accidentally avoid using `InputFile`

Require using InputFile class

---

node-backport/package.json

This makes npm display a TypeScript badge on the package site.

Add types property to package.json

---

deno/src/bot.ts
deno/src/composer.ts
deno/src/core/client.ts
deno/src/core/error.ts

Fixes a bug in error boundaries.
Makes grammY ready for error handling in TypeScript 4.4 where errors in `catch` blocks will be of type `unknown` by default.
Improves the default error message that is printed if `BotError` is logged instead of properly inspecting the thrown error object.
Adds an option to print sensitive information to the logs, called `sensitiveLogs`. This will make the API client include the bot token in error messages, but as an advantage, more detailed system information become available when network requests fail. This option will be recommended to set to `true` for production scale bots in the deployment checklist.

Improve error handling

---

deno/src/bot.ts
deno/src/context.ts
deno/src/core/api.ts
deno/src/core/client.ts
deno/src/mod.ts
deno/src/platform.ts
node-backport/package.json
node-backport/platform.ts

Just as the context type can be adjusted, this PR introduces a type parameter for the API type.
It is used only for `bot.api` because `ctx.api` can already be adjusted via the context type. Also, we do not want to make a mess by having the context type depend on the API type.
This PR is required for a future implementation of a hydration plugin.
This PR is required by the code in the files plugin repository: https://github.com/grammyjs/files

Support custom API types

---

deno/src/core/client.ts
node-backport/package.json

Downgrades to `node-fetch@2` in order to fix module resolution.
Downgrades to `@types/node@12` because that is the minimum requirement for grammY.
Updates all other dependencies to their latest versions.

Fix dep versions

---

deno/src/core/payload.ts

This PR leverages [the fact](https://github.com/tdlib/telegram-bot-api/issues/167) that the Bot API can process all file uploads via `attach://` strings, even though this is not documented on the website.

Always rely on attach:// strings

---

deno/src/core/client.ts

This will throw an error upon bot creation of the `client.apiRoot` option contains a trailing slash. The kind of configuration is hard to debug, because Telegram simply returns a 404.
This PR also gives away more info in case Telegram returns errors that are hard to understand. It does this by printing sensitive logs (if enabled) also in case the error is returned by Telegram.

Check API root for trailing slash

---

package.json
src/context.ts
src/core/api.ts
src/filter.ts
src/platform.deno.ts

Updates grammY to Bot API 5.4.
Also updates the Deno std lib to 110. If someone knows where `iter` is in more recent versions, please let me know and we can update the dep to 113.

Update to Bot API 5.4

---

src/platform.deno.ts
src/platform.node.ts

Adds the following syntax for constructing `InputFile`s based on remote data.
```ts
const url = 'https://raw.githubusercontent.com/grammyjs/website/main/logos/grammY.png'
// both work
new InputFile({ url })
new InputFile(new URL(url))
```
The data will be fetched lazily from the specified URL as soon as the `InputFile` is sent. The file contents are streamed, so only a small portion of the data is kept in memory at all times. When several files are sent in an album, they are piped though one by one, such that only a single outgoing request is open at all times.
Currently does not support more advanced configuration options. Note that it's already possible to do this:
```ts
const { body } = await fetch(url, opts)
if (body === null) throw new Error('No data')
const inputFile = new …
```

Support creating InputFile instances from URLs

---

src/filter.ts

There was 3 message entity types missing (https://core.telegram.org/bots/api#messageentity) in src/filters.ts. `pre`, `text_link`, `text_mention`. Added those.

Added missing pre, text_link, text_mention entity types to filters

---

src/core/client.ts
src/core/payload.ts
src/platform.deno.ts

If an iterator throws, the corresponding stream causes an unhandled promise rejection. This is an ugly specification, and this PR work around it by wrapping the iterator and cancelling the request upon error.
Closes #34.
Uses ideas from https://github.com/denoland/deno_std/issues/1214.

Catch throwing iterators

---

src/platform.deno.ts
src/platform.node.ts

Adds support for `Blob` under Deno.
Adds support for `Deno.File` under Deno. This allows for:
```ts
new InputFile(await Deno.open('/path/to/file'))
```
Also adds support for passing a `Promise` of any value under both Deno and Node.js. This allows for:
```ts
new InputFile(Deno.open('/path/to/file'))
```
under Deno, as well as
```ts
import { promises as fs } from "fs";
new InputFile(fs.readFile("asdf"));
```
under Node.
Note that this change will be integrated into #77 in order to prevent conflicts.

Support file uploads via Deno.open()

---

src/core/client.ts

This little change allows user to control `compress` property (as well as the other possible options) without need to manually specify `agent`. In example I want to disable compression (it's enabled by default for `https` apiRoot) with default bot API server. With this change I can use:
```javascript
const bot = new Bot(TOKEN, {
client: {
baseFetchConfig: {
compress: false,
},
},
});
```
instead of:
```javascript
import { Agent as HttpsAgent } from "https";
const bot = new Bot(TOKEN, {
client: {
baseFetchConfig: {
compress: false,
agent: new HttpsAgent({ keepAlive: true })
},
},
});
```
Or when I want compression with local bot api server (it's disabled by default for http) I can use:
```javascript
const bot = new Bot(TOKEN, {
client: {
apiRoot: "http://local.server.lan:12345/", …
```

Improved building config of ApiClient

---

src/platform.deno.ts
src/platform.node.ts

This is already working, all we need to do is to permit it in the type annotations.
What's more, we're already expecting this to work in the docs: https://grammy.dev/guide/files.html#uploading-your-own-files

Support synchronous iterables

---

src/context.ts

If there is not match, then `ctx.match` will be `undefined`. If a match is found, it will be either a string or a match array. Either way, `null` is not a possible type.
This PR removes `null` from the `ctx.match` type.
Follow-up for #81, see https://github.com/grammyjs/grammY/pull/81#discussion_r744256477

`ctx.match` cannot be `null`

---

README.md
package.json
src/context.ts
src/convenience/keyboard.ts
src/core/api.ts
src/filter.ts
src/platform.deno.ts

Adds support for Bot API 5.5.
The only _interesting_ grammy-specific change is that we can now do:
```ts
bot.on('message:is_automatic_forward')
```
and it will trigger for all messages in a group that were posted in the attached channel.

Add support for Bot API 5.5

---

src/bot.ts
src/convenience/session.ts

Fixes errors reported in https://t.me/grammyjs/16197 and https://t.me/grammyjs/28217, namely that `bot.stop()` caused the built-in polling to throw an error.

Fix throwing error upon `bot.stop()`

---

src/composer.ts

With `composer.command('/start')`, the expected error message is:
```Do not include '/' when registering command handlers (use 'start' not '/start')```
but instead I received
```Do not include '/' when registering command handlers (use '/' not '/start')```

Fix error for command with a leading slash

---

bundling/bundle-all.sh

When Deno (and thus TS) upgrades, this can make already released versions stop compiling. That just happened with TS 4.5. Such a case breaks our bundling script. This PR applies `--no-check` to all bundling operations, and it does so with the following reasons:
- All versions typecheck when released. This is enough safety.
- Bundles do not contain types, and since tsc transpilation JS output is stable over versions due to regression tests, we can safely ignore the types in the code.
- It takes a lot of time to check the same stuff over and over again, which slows down CI by a large factor.
- Bundling is broken and there are no other solutions that take this little effort and work that well.

Skip typechecks while bundling old versions

---

bundling/bundle-es.ts

Fixes up on #116 by removing ES3 and ES5 bundles. See https://github.com/grammyjs/grammY/pull/116#issuecomment-997482092 for why this is done.
The versions are also going to be removed from the CDN. They are broken and cannot possibly work, so they have zero purpose and should have zero usage.

Remove broken ES3 and ES5 bundles

---

package.json
src/platform.deno.ts
test/bot.test.ts
test/filter.test.ts

Title says it all. Achieved by updating type deps. No code changes required.
Related: https://github.com/grammyjs/types/commit/17c50c4b5eaab5e407e90ab46e91cc497ede58e7

Update to Bot API 5.6

---

README.md
package.json
src/context.ts
src/core/api.ts
src/platform.deno.ts
test/bot.test.ts
test/filter.test.ts

Updates grammY to Bot API 5.7.
Blocked by https://github.com/grammyjs/types/pull/5.
Pending tasks:

Update to Bot API 5.7

---

src/core/client.ts
src/platform.deno.ts

This is breaking, but only for Deno users who do an update of Deno which deprecates `Deno.File` and makes their linting fail.
Fixes CI.
Includes #173.

Migrate from `Deno.File` to `Deno.FsFile` and merge #173

---

src/bot.ts

If one does
```ts
bot.start()
await bot.init()
```
then this would make grammY perform two identical calls to `getMe`.
This PQ optimizes the above scenario. Any number of calls will be deduplicated automatically, so that all promises resolve at the same time when the first `getMe` call completes.
In addition, the initialization via `bot.init` is made more robust by automatically retrying the API call if there are network issues. Previously, this was only the case for init calls done via `bot.start`.

Deduplicate concurrent calls to `bot.init`

---

src/bot.ts
src/convenience/webhook.ts

Follow-up for #182.
The webhook callback now makes use of the introduced deduplication of init calls. Previously, it had its own way to making sure that only one update would load to the call.

Fix double deduping

---

src/platform.deno.ts

That's how it was before Deno decided to always prompt by default. This PQ restores the old behaviour.

Avoid prompting for DEBUG env var access

---

src/core/client.ts

Drops the custom `Await` type, and replaces it by the recently introduced `Awaited` type which was added to TS.

Use built-in Awaited type

---

src/context.ts

Fix typo.
Accidentally swapped the terms in commit message.

Fix doc typo: whereever -> wherever

---

.github/release.yml
.github/workflows/cdn.yml
.github/workflows/commitlint.yml
.github/workflows/deno.yml
.github/workflows/release.yml
README.md

- Initialized commitlint workflow to enforce the Conventional Commits style for commit messages.
- Initialized release workflow to creat releases with automatically-generated release notes on tag creations.
- Updated the versions for `actions/checkout`.

feat(ci): release & commitlint workflows

---

deno.jsonc
package.json

Regarding https://github.com/grammyjs/grammY/pull/224#discussion_r884245894. Is this what you meant?

chore: remove npm scripts not required for GitHub installs

---

src/convenience/frameworks.deno.ts
src/convenience/frameworks.node.ts
src/convenience/webhook.ts

Check out the new https://core.telegram.org/bots/api#setwebhook

Add support for secret header validation

---

src/convenience/frameworks.node.ts

Fastify will normalize all headers to lower case form, so we always get `undefined` by using `req.headers[SECRET_HEADER]`.
This PR fixes that by using `toLowerCase` to transform the given header key.
Not sure If CloudFlare or AWS Lambda will do that too, so they are leaved unmodified.

Fix fastify webhook updates when secretToken given

---

src/context.ts

As reported by @EdJoPaTo and discussed in https://t.me/grammyjs/65534

fix: `ctx.match` being absent

---

src/context.ts
src/filter.ts
test/composer.test-d.ts

fix: plugin types compatibility issue with ctx.has

---

.vscode/settings.json

as discussed in https://grammyjs.t.me/73886

chore: make deno the default formatter for VSCode

---

src/composer.ts

Currently, routing can only be done with strings according to the type system. However, at runtime, we actually already support numbers and symbols as identifiers for the route handlers. This PQ adjusts the types to allow for all working values.
Note that this enables the following use case.
```ts
bot.route<Record<number, Middleware<C>>>((ctx) => ctx.session.step++, [
(ctx) => ctx.reply("I am at 0"),
(ctx) => ctx.reply("I am at 1"),
(ctx) => ctx.reply("I am at 2"),
(ctx) => ctx.reply("I am at 3"),
(ctx) => ctx.reply("I am at 4"),
]);
```

fix: support numbers and symbols in `bot.route`

---

src/convenience/session.ts

Fixes CI. Necessary adjustment for the new handling of `{}`.

fix: add support for TS 4.8

---

src/convenience/frameworks.node.ts

This adapter will enable bots to work smoothly when using next.js api routes as webhook endpoint. See https://t.me/grammyjs/86659 for how it started.

feat: webhook adapter for next.js api routes

---

src/context.ts

Narrow match for callback query

---

.gitignore
package.json
src/types.deno.ts

Necessary after Deno 1.28 was released which started generating this file automatically: https://deno.com/blog/v1.28#auto-discovery-of-the-lock-file

Ignore deno.lock file from source control

---

src/context.ts
src/core/api.ts

I noticed that  "choose_sticker" chat action is missing so I made this pull request to add it

 Fix: missing chat action added "choose_sticker"

---

CONTRIBUTING.md

This was changed a long time ago already and the document should reflect it.

docs: mention storage adapter repo in contrib guide 

---

src/convenience/frameworks.deno.ts
src/convenience/frameworks.shared.ts

oak has Node builds.
As Node slowly starts taking in the same standards that Deno supports, it makes sense to allow Node users to adapter the API from Deno's standard library.

feat: allow Node users to leverage std/http and oak adapters

---

bundling/bundle-all.sh
bundling/bundle-web.ts
deno.jsonc
package.json
src/platform.deno.ts
src/platform.web.ts
src/types.web.ts
tsconfig.json

Besided being called inside `bundle-all.sh`, `deno task bundle-web` can also be used to create the new bundle.
Two files will be created inside the `out` folder: web.js and web.d.ts
The `web.d.ts` file only re-exports everything from `out/mod.d.ts`. This
file is needed because typescript refuses to search for types for the
`web.js` file in anywhere other than a `web.d.ts` placed next to it.
That behavior should be overriden by the `typesVersions` property in
`package.json`, but for some reason it's not. The `typesVersions`
property is necessary to make typescript detect the `/web` entrypoint,
though.

feat: built-in web bundle

---

.github/workflows/release.yml

The action will run whenever a `v1.*` tag is created pointing to `main`.
It will call `npm publish`, which will run `npm run backport`
because of the `prepare` npm script.

chore: add github action to publish to npm

---

.github/workflows/release.yml
package.json

We need to create the web version before publishing the package so the web.mjs and web.d.ts files exist when we `npm publish`

chore: run web bundle before npm publish

---

.gitignore
package.json

It could be the case that bundling fails as the tightly restricted list of directory for `--allow-write` meant that deno could not write to deno cache, as it is not specified.
This PR attempts to specify a well-known path for deno cache so that it can be specified in the list of directory for `--allow-write`, in an attempt to resolve the current build error.

chore: try using a well-known deno_cache for automated web bundle

---

src/convenience/session.ts
test/convenience/session.test.ts

Prevents non-TS people from making the same mistake as reported in #345.

feat: protect against lazy multi sessions mistake

---

package.json
src/context.ts
src/convenience/keyboard.ts
src/core/api.ts
src/filter.ts
src/types.deno.ts
test/convenience/keyboard.test.ts

https://core.telegram.org/bots/api#december-30-2022
There is a small breaking change in this release. Two paramters in `editFormTopic` have become optional. As a result, they were removed from the respective method in `Api`. This is a known disadvantage of the convenience of having parameters in the function signature.

feat: add support for Bot API 6.4

---

src/convenience/frameworks.deno.ts

We already receive a JSON string, passing it to `JSON.stringify` seems wrong. I need someone to confirm this, though.

fix: do not JSON.stringify twice for serveHttp adapter

---

src/convenience/frameworks.node.ts
src/convenience/frameworks.shared.ts
src/convenience/frameworks.web.ts
src/convenience/webhook.ts

So far, only worktop is supported. With this PQ, we can do
```ts
addEventListener('fetch', webhookCallback(bot, "cloudflare"))
```

feat: add native CloudFlare Workers adapter

---

src/core/api.ts

It should be `get...` not `set...` in the `other` parameter.

fix: incorrect type in `getMyDefaultAdministratorRights`

---

deno.jsonc
package.json
src/bot.ts

Makes sure that `bot.init` does not retry too fast.
Allows passing an `AbortSignal` to `bot.init` so the initialization process can be cancelled anytime.
Makes sure that calling `bot.stop` will abort any pending initialization.
Makes sure that polling does not start if the bot is stopped while the `onStart` callback is running.
Closes #291.

feat: exponential backoff for retries and permit cancelling `bot.init`

---

src/bot.ts

Sets some internal flags correctly so that built-in polling can be used again.
Fixes #382.

fix: built-in polling not starting

---

package.json

Makes TypeScript aware of where the types for `grammy/types` are actually located.

fix: add typesVersions for /types export

---

src/core/payload.ts
src/platform.deno.ts
src/platform.node.ts
src/platform.web.ts
src/types.deno.ts
src/types.node.ts
src/types.web.ts

A common issue is that mismatches between patch versions lead to type errors. This can happen when a plugin imports a version of grammY that is different from the version of grammY that the bot code uses, or if two plugins rely on different versions of grammY.
At runtime, these mismatches do not cause any problems because grammY follows semver, and it also does not rely on any `instanceof` checks that could break due to different class identities. Hence, small version mismatches cause needlessly much headache.
The main contributor to these errors is the symbol that is used in `InputFile`. `InputFile` is a parameter of many API methods. API methods are used in the `Api` class. The `Api` class has an instance which is on the context object at `ctx.api`. The context type is checked in many …

refactor: avoid using a symbol for input files

---

src/convenience/frameworks.ts

Next JS header keys are lower. The fix is simple … just make the header key lowercase as is already done for a few other adapters (fastify, http)
`api/init.ts`
```ts
const bot = new Bot(env.TELEGRAM_BOT_API_TOKEN, { botInfo });
async function handler(request: NextApiRequest, response: NextApiResponse) {
await bot.api
.setWebhook(env.TELEGRAM_WEBHOOK_URL, {
secret_token: env.TELEGRAM_WEBHOOK_SECRET,
})
.then((_) => bot.api.getWebhookInfo())
.then((data) => {
console.log(data);
response.status(200).json({
body: "OK",
});
})
.catch((error) => {
console.log(error));
response.status(500).json({ error });
});
}
export default handler;
```
`api/listen.ts`
```ts
const bot = new Bot(env.TELEGRAM_BOT_API_TOKEN, { botInfo });
bot.on("message:text", async (ctx) => {
console.log(ctx);
await …
```

Webhook Secret Token fix for NextJS

---

src/composer.ts
src/convenience/keyboard.ts
src/core/api.ts

docs: fix broken links

---

src/convenience/frameworks.ts

Changes:
- feat: add aws-lambda-async webhookCallback adapter
- fix: apply correct headers to aws-lambda webhookCallback adapter
I did not find any relevant test cases covering adapters, so I am opening this PR with just a few manual tests.

Improve aws-lambda webhookCallback adapter

---

src/composer.ts
src/platform.deno.ts

The web build will benefit from this because it can now be used in environments that do not support TLA.
Fixes #405.

refactor: avoid top-level await

---

package.json

fix: add `"node"` condition to `"."` entry point

---

src/core/api.ts

Replaced wrong link for `answerWebAppQuery` api

fix reference link for `answerWebAppQuery`

---

src/composer.ts
src/platform.deno.ts

Reverts grammyjs/grammY#436.
Deno Deploy does and and will never support sync APIs. However, we do see increasing support for TLA, with CFW being the most important runtime.

Revert "refactor: avoid top-level await"

---

package.json

**Vercel Edge Runtime** need a different key in `"exports"` for **web** target
If we add a `"browser"` target, **Vercel Edge Runtime** can automatically switch to **web** build instead specifying it manually:
```js
import { Bot } from "grammy/web"; // now
import { Bot } from "grammy"; // after merge
```
Also, this can solve incompatibility for some plugins that not depend on **Node** internal packages, but uses default import for core **grammY** package
I think we need to test this change on other platforms before merging 🌚
```json
{
"dependencies": {
"grammy": "npm:@ponomarevlad/grammy@1.17.0-vercel-edge"
}
"overrides": {
"grammy": "npm:@ponomarevlad/grammy@1.17.0-vercel-edge"
}
}
```
> [Complete example for Vercel Edge Runtime](https://github.com/PonomareVlad/grammYVercelEdge/tree/main)

Package exports for Vercel Edge Runtime support

---

src/filter.ts

`object` was now finally allowed by `deno lint` so we can get rid of that ugly helper type alias.

refactor: inline SomeObject type alias

---

src/convenience/frameworks.ts

Tested by [this](https://github.com/PonomareVlad/grammYExportsTest/blob/express/index.mjs) example 🙂

Fixed use of deprecated express method

---

src/context.ts
src/convenience/constants.ts
test/context.test.ts

Exports `DEFAULT_UPDATE_TYPES` from grammY.
Exports a new `interface ApiConstants` which provides types for `API_CONSTANTS`.
Closes #453 which has several problems:
- it provides two very similar interfaces called `ApiConstants` and `API_CONSTANTS` which is maximally confusing
- one of the two interfaces is not documented at all, but it is the more useful one
- there is no link from the values to the types in the generated Deno module docs
This PQ fixes all of that.

feat: add types and improved docs for API_CONSTANTS

---

src/platform.web.ts

fix(web): do not rely on ReadableStream.from

---

src/core/client.ts

In https://t.me/grammyjs/168114 and so many other times, people who do not use TS (and who do not read docs) use the context shortcuts and other methods incorrectly. This PQ attempt to explain to them how to fix their code.

feat: prevent incorrect signal usage

---

src/bot.ts
src/convenience/frameworks.ts

This PR adds support for [nhttp](https://nhttp.deno.dev/) for webhook handler.

support `nhttp` for webhook handler

---

src/core/client.ts

Requested in https://t.me/grammyjs/190672
Use it like so:
```ts
const bot = new Bot("token", {
client: { environment: "test" },
});
```

feat: simplify using Test DC

---

package.json

Should fix
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './types' is not defined by "exports"
```

fix: properly define the subpath ./types in exports

---

src/convenience/frameworks.ts

Experiencing the following errors when using Hono and grammY.
```
2024-02-10T06:11:33.126 app[90806145c55418] syd [info] 123 | /** hono web framework */
2024-02-10T06:11:33.126 app[90806145c55418] syd [info] 124 | const hono = (ctx) => {
2024-02-10T06:11:33.126 app[90806145c55418] syd [info] 125 | let resolveResponse;
2024-02-10T06:11:33.126 app[90806145c55418] syd [info] 126 | return {
2024-02-10T06:11:33.126 app[90806145c55418] syd [info] 127 | update: ctx.req.json(),
2024-02-10T06:11:33.126 app[90806145c55418] syd [info] 128 | header: ctx.req.headers.get(SECRET_HEADER) || undefined,
2024-02-10T06:11:33.126 app[90806145c55418] syd [info] ^
2024-02-10T06:11:33.126 app[90806145c55418] syd [info] TypeError: undefined is not an object (evaluating 'ctx.req.headers.get') …
```

Fix hono adapter

---

README.md
package.json
src/context.ts
src/convenience/session.ts
src/core/api.ts
src/filter.ts
src/types.deno.ts
src/types.web.ts
test/context.test.ts

https://core.telegram.org/bots/api#march-31-2024

feat: support Bot API 7.2

---

deno.jsonc
src/platform.deno.ts
src/types.deno.ts
test/core/payload.test.ts
test/deps.test.ts
test/types.test.ts

1. `iterateReader` was deprecated. See: <https://deno.land/std@0.211.0/streams/iterate_reader.ts?s=iterateReader>.
2. `Deno.open` need to release resources. Deno provided `using` keywords for this purpose. Like this: <https://github.com/denoland/deno/blob/08f46ac4467968f53400c4cf9db95f62b424a161/cli/tsc/dts/lib.deno.ns.d.ts#L1891>
3. `importMaps`, it would be more convenient, if `grammy` and `grammy_type` were to be published JSR. (Like: `deno add`)

refactor: prefer FsFile#readable over std/iterateReader

---

src/convenience/constants.ts

As discovered during a talk by @roziscoding at https://events.geekle.us/typescript24/

doc: add missing updates to docs of API constants

---

.github/workflows/deno.yml
src/convenience/frameworks.ts

How did we never type-check grammY in CI? It currently fails and I only discovered this locally.

chore(ci): type-check library in CI

---

README.md
package.json
src/context.ts
src/convenience/keyboard.ts
src/core/api.ts
src/filter.ts
src/types.deno.ts
src/types.web.ts

https://core.telegram.org/bots/api#may-28-2024

feat: support Bot API 7.4

---

src/filter.ts
test/composer.type.test.ts

First reported in https://t.me/grammyjs/248339

fix: resolve type conflict of ctx.chatId for callback queries

---

src/convenience/webhook.ts

First reported in https://t.me/grammyjs/248742

fix: unify webhookCallback overloads

---

src/composer.ts
src/context.ts
test/composer.test.ts
test/composer.type.test.ts
test/context.test.ts

This PQ adds `preCheckoutQuery()` and `shippingQuery()` to `Composer`. Developers can write regular expression to match the invoice payload of pre-checkout queries and shipping queries.

feat: add `bot.preCheckoutQuery` and `bot.shippingQuery`

---

README.md
package.json
src/context.ts
src/core/api.ts
src/filter.ts
src/types.deno.ts
src/types.node.ts
src/types.web.ts

https://core.telegram.org/bots/api#july-1-2024

feat: support Bot API 7.6

---

src/composer.ts
src/context.ts

In response to https://t.me/BotNews/96, the right thing to do is to suggest developers to add a section about privacy.

feat: suggest "privacy" commands

---

src/convenience/webhook.ts

grammY already throws an error in these cases,
but sometimes, people don't put their errors in
the logs. This will fix that.

feat: log webhook timeout in DEBUG mode

---

deno.jsonc

Maybe there is some meaning behind this why it isn't used yet. Backwards compatibility? But the two entries are not equal so moving them to a single place provides a single point of truth there that can't diverge.

build: move exclude to deno.jsonc top level

---

src/context.ts

This is suggested in https://telegram.org/privacy-tpa so maybe embrace this a bit more?
See also #610

feat: suggest /developer_info as a command

---

src/convenience/session.ts

Will merge without review, sorry

style: reflow docs text in sessions

---

deno.jsonc
package.json
src/context.ts
src/convenience/frameworks.ts
src/core/api.ts

The JSDocs for `api.sendDice` and `ctx.replyWithDice` were missing '🎳'  so I brought them up to date with the latest changes on https://core.telegram.org/bots/api#senddice.
I also added suggestions for the parameter `emoji` following the style in `sendChatAction`. It might be reasonable to remove `| (string & Record<never, never>)` but I didn't want to introduce a breaking change.
I also fixed two JSDocs with an incorrect link to the documentation.

build: update deno2node, fix docs, add suggestions to sendDice

---

.github/workflows/deno.yml
.github/workflows/release.yml
.github/workflows/third_party.yml
deno.jsonc
test/core/client.test.ts

Run `deno upgrade rc` and execute all tests to see that this works.

chore: make tests compatible with Deno 2.0

---

src/bot.ts

Adds a way to inspect whether or not the bot is currently running.

feat: `bot.isRunning()`

---

src/convenience/webhook.ts

People sometimes do
```ts
webhookCallback(bot)
bot.start()
```
or
```ts
bot.start()
webhookCallback(bot)
```
and in 99 % of cases, this is just wrong.
This PQ interdicts this type of usage and throws a helpful error message.
If this is actually desired (run the bot on built-in polling but then also supply old updates from a webhook queue, whatever) then it can be done anyway:
```ts
const middleware = new Composer()
middleware.use(..) // etc
const pollingBot = new Bot(token)
const webhookBot = new Bot(token)
pollingBot.use(middleware)
webhookBot.use(middleware)
pollingBot.start()
webhookCallback(webhookBot)
```

feat: detect concurrent polling/webhook setups and throw error

---

test/deps.test.ts

After https://github.com/denoland/std/pull/6154 was accepted, we no longer need to rely on our implementation of it. This PQ replaces it with the implementation from @std.

build: move helper type to JSR

---

src/core/client.ts

This pull request introduces a new feature to the `ApiClient` class in `src/core/client.ts` to allow custom `fetch` functions. This enables more flexibility in making HTTP requests, especially in different environments like Node.js and Deno.

feat: add customizable fetch function to ApiClientOptions

---

src/core/client.ts

As reported in https://t.me/grammyjs/279613

fix: handle abort signal for methods without payload

---

src/convenience/session.ts
test/convenience/session.test.ts

With multi sessions and the conversations plugin, storage adapters are used in many places. It needs to be made simple to store session data under namespaces. This PQ does that by adding a new option `prefix` to session config. The prefix will be prepended to every session key before reading, writing, or deleting data.

feat: add custom prefix for session key

---

README.md
package.json
src/context.ts
src/convenience/frameworks.ts
src/core/api.ts
src/types.deno.ts
src/types.web.ts

https://core.telegram.org/bots/api#january-1-2025

feat: support Bot API 8.2

---

src/convenience/frameworks.ts

Following the fix in #734, this improves the way we model hono usage internally

refactor: model hono types more accurately

---

src/convenience/frameworks.ts

As mentioned in https://github.com/grammyjs/grammY/issues/737#issuecomment-2595376501

type: fix Azure Function v4 Adapter HttpRequest and InvocationContext Type

---

src/convenience/frameworks.ts
src/convenience/webhook.ts
test/convenience/webhook.test.ts

PR aiming to close https://github.com/grammyjs/grammY/issues/695 and https://github.com/grammyjs/grammY/issues/696
I'm not good at typing, so I'm requesting help. There are couple "as" in a commit :)
I created a factory of factories to dynamically generate object with creators of callback handlers. I do not know how to document every object property in this case. If it is not necessary, we can just describe the main object.
Regarding the "return" type, I decided to rename it to "ignore" because it does not make any calls and leads to a safe logic branch. The user can pass an empty callback as an argument, and it will work pretty much the same, but with an unnecessary extra call.
So, if we want to slim down and simplify the API, we need to remove "ignore." If we want to gain a nano …

refactor(webhook): change the way to get webhook handler 

---

deno.jsonc
src/convenience/frameworks.ts
src/convenience/webhook.ts
test/convenience/webhook.test.ts

The issue was originally described here: https://github.com/grammyjs/grammY/issues/613
**Short Summary:**
We assume that the body will be valid JSON. However, it can be empty or contain invalid JSON in some unusual cases. This can cause the server to crash due to an uncaught error triggered by JSON parsing in some of the adapters.
It was suggested to wrap it in a function, but I think that is unnecessary. We already have a promise and just need to safely resolve it to a value that we can then validate.
I suggest catching all promises where a crash can occur and returning an empty object. In `webhookCallback`, we can perform basic validation by checking the `update_id` field. In the case of an invalid body, we should return a 400 status to the client. Here, we need to add an extra callback …

feat: fault tolerant body handling

---

.github/workflows/deno.yml

This lets us view CI when working on #675.

chore(ci): run CI on all branches and v2 pull requests

---

README.md
package.json
src/context.ts
src/core/api.ts
src/types.deno.ts
src/types.web.ts

https://core.telegram.org/bots/api#february-12-2025

feat: support Bot API 8.3

---

src/convenience/frameworks.ts

Adds a new webook adapter following https://learn.microsoft.com/en-us/azure/azure-functions/functions-node-upgrade-v4
Fixes https://github.com/grammyjs/grammY/issues/737

feat: add support for Azure Functions v4

---

src/filter.ts

The filter queries were still written with TS pre-3.5 in mind. `{}` actually means “anything except null or undefined” nowadays (for a long time already) so we should be able to rely on this in order to remove undefined.
Reported in https://t.me/grammyjs/296604

fix: reduce `NotUndefined` to `{}`

---

src/core/api.ts

docs: fix typo in `Api` description

---

src/filter.ts

Based on [the message_thread](https://grammyjs.t.me/300334)
Please let me know if this is expected approach.

feat: add filter query for link_preview_options

---

src/types.deno.ts
src/types.web.ts

The old std no longer compiles. We need to update the version, and thus change the registry.
This only affects Deno-specific code. The Node build output will be byte-identical.

build: prefer jsr.io/@std over deno.land/std

---

bundling/bundle-web.ts
deno.jsonc

The old deno_emit does not support JSR but it needs to do that after #802. We need to update the version, and thus change the registry.
This only affects the web build.

build: update deno_emit from JSR

---

bundling/bundle-web.ts

There used to be a bug that source maps were generated even though we had disabled them. This was fixed, so we can remove the workaround.
Likely related to #804.

build: remove workaround that strips source maps

---

src/convenience/frameworks.ts
src/convenience/webhook.ts

More explanation here: https://github.com/grammyjs/grammY/pull/816#issuecomment-3180716466
We turned `ReqResHandler::update` into a getter to allow handling update promises lazily without breaking API.

fix: unhandled rejections from lazy promise handling

---

src/context.ts

Regular message in general topic
```ts
sendMessage
{
chat_id: 41284431,
text: "hi",
business_connection_id: undefined,
direct_messages_topic_id: undefined,
}
```
Regular message in test topic
```ts
sendMessage
{
chat_id: -1003070712535,
text: "hi",
business_connection_id: undefined,
message_thread_id: 2,
direct_messages_topic_id: undefined,
}
```
Reply to (and reply to reply to, and so on) messages in general topic
```ts
sendMessage
{
chat_id: -1003070712535,
text: "hi",
business_connection_id: undefined,
direct_messages_topic_id: undefined,
}
sendMessage
{
chat_id: -1003070712535,
text: "hi",
business_connection_id: undefined,
direct_messages_topic_id: undefined,
}
sendMessage
{
chat_id: -1003070712535,
text: "hi",
business_connection_id: undefined,
direct_messages_topic_id: undefined,
} …
```

fix: add is_topic_message check before setting message_thread_id

---

src/context.ts

When sending messages to other chats, we must not transfer the thread identifier of the origin chat to the target thread.

fix: do not pass message_thread_id to unrelated chats

---

bundling/bundle-web.ts
deno.jsonc
package.json
src/platform.deno.ts
src/platform.web.ts
src/types.deno.ts
src/types.web.ts
test/convenience/webhook.test.ts

- updates all deps to latest of the same major version
- suppresses new linting rules that do not apply to libraries

build: update all deps, ignore new linting rules
