- .github/workflows/deno.yml
Set up CI that run `deno test` on commits to `main`.
> Add CI config

- deno/src/core/payload.ts
> Switch from AsyncGenerator to AsyncIterable return types

- deno/src/bot.ts
Does not stop polling after one hour.
Also now retries upon all errors, not just API errors.
> Retry `getUpdates` calls indefinitely when polling

- .github/workflows/deno.yml
- deno/src/bot.ts
- deno/src/core/error.ts
- deno/src/platform.ts
- deno/test/bot.test.ts
- deno/test/filter.test.ts
Title says it all. Updates to `0.97.0`.
> Update Deno std lib and add linting to the CI pipeline

- deno/src/platform.ts
Title says it all.
Fixes #15 
Closes #16
> Support Deno Deploy

- deno/src/core/client.ts
> Chance default options reception

- deno/src/core/client.ts
> Fix error message

- src/context.ts
Title says it all. Discussed in https://t.me/grammyjs/21243
> Permit strings for callback and pre-checkout queries

- src/composer.ts
Also see https://github.com/grammyjs/router/commit/982dfee2bdf6010e38a127fd638135d3dc2a6b20
> Fix wrong update routing in composer

- src/bot.ts
Certain network issues cannot be handled automatically by the library consumer, so it does not make sense to throw these errors. Instead, grammY will now print some debug output and retry.
> Retry network calls during initialization

- src/core/client.ts
… by adding a single `deno-lint-ignore` comment.
> Add support for Deno 1.16

- .all-contributorsrc
- README.md
Small PR in order to edit my contributors name
> [chore]: Edit name of contributor

- README.md
> Fix remaining links

- src/context.ts
- src/filter.ts
> Add chat join requests to ctx.chat/ctx.from sources

- src/convenience/session.ts
Title says it all. Requested in https://t.me/grammyjs_ru/101
> Add `readAll` and internal data access to memory session

- src/context.ts
- src/core/api.ts
Title says it all. Reported in https://t.me/grammyjs/28301
> Fix not permitting start parameter in sendInvoice

- src/convenience/keyboard.ts
- src/filter.ts
Aligns inline docs with https://github.com/grammyjs/website/pull/162
> Rename keyboards to custom keyboards in docs

- src/convenience/session.ts
Closes #137 
Closes #138 by fixing the same error but without changing the runtime code
> Add compatibility to TS 4.5

- src/bot.ts
> Add bot.isInited()

- src/filter.ts
Fixes #157.
Please review very thoroughly. This is a fragile part of the library, and it is nearly impossible to write automatic tests for it. Just throw it onto a large grammY code base and check that everything still compiles. I tried out a bunch of toy examples for testing purposes, but it would be nice to have an independent confirmation that this works.
> Implement cross-level twins

- src/bot.ts
Refactors the built-in polling to be a lot more readable by extracting the different parts into methods.
Correctly handles 429 errors thrown during polling. These are never thrown during normal operation, but can happen while the Bot API server is closing. In that case, the returned `retry_after` value should be respected, which is what this PQ is doing now.
This must be reviewed from Deno 1.17.1 or from Node.js because https://github.com/denoland/deno/issues/13469 prevents grammY from working on Deno>=1.17.2 at the moment.
> Refactor polling and handle 429 errors

- src/core/client.ts
- src/platform.deno.ts
> fix: fetch type for Deno 1.20.3

- src/convenience/session.ts
As discussed in https://t.me/grammyjs/44217
> Improve error message for undefined session key

- .github/workflows/deno.yml
- .gitignore
- .vscode/settings.json
- CONTRIBUTING.md
- deno.jsonc
- package.json
- src/core/payload.ts
- src/platform.deno.ts
- test/bot.test.ts
- test/composer.test.ts
- test/core/client.test.ts
- test/core/error.test.ts
- test/core/payload.test.ts
- test/filter.test.ts
Adds a lot of drafts for the tests we always should've had.
> Add tests for most of the library

- src/convenience/keyboard.ts
- test/convenience/keyboard.test.ts
- test/convenience/session.test.ts
> feat(test): add tests for built-in plugins

- src/convenience/frameworks.deno.ts
- src/convenience/frameworks.node.ts
- src/convenience/frameworks.shared.ts
As requested in https://t.me/grammyjs/65130
> feat: make express, koa, fastify available on Deno

- src/context.ts
> fix: stricter chat type types

- CONTRIBUTING.md
- README.md
- src/bot.ts
- src/composer.ts
- src/context.ts
- src/convenience/keyboard.ts
- src/convenience/session.ts
- src/convenience/webhook.ts
- src/core/api.ts
- src/core/client.ts
- src/core/payload.ts
- src/types.deno.ts
- src/types.node.ts
Fixed various typos in comments.
> chore: fix typos

- package.json
- src/composer.ts
- src/context.ts
- src/convenience/frameworks.deno.ts
- src/convenience/frameworks.node.ts
- src/convenience/session.ts
- src/convenience/webhook.ts
- src/core/api.ts
- src/core/payload.ts
- src/filter.ts
- src/platform.deno.ts
- src/types.deno.ts
- src/types.node.ts
Also updates deps, docs, and rearranges imports based on Deno's new feature
> feat: update to Bot API 6.2

- README.md
As requested in https://t.me/grammyjs/82935
> docs: list Awesome grammY in README

- src/convenience/frameworks.node.ts
Adds support for https://kit.svelte.dev/
> feat: add SvelteKit adapter

- deno.jsonc
- package.json
- src/platform.deno.ts
- src/types.deno.ts
- test/bot.test.ts
- test/composer.test.ts
- test/context.test.ts
- test/convenience/keyboard.test.ts
- test/convenience/session.test.ts
- test/core/client.test.ts
- test/core/error.test.ts
- test/core/payload.test.ts
- test/filter.test.ts
> chore: update deps

- .github/workflows/release.yml
- src/types.web.ts
> fix: cannot npm ci without lock file

- CONTRIBUTING.md
This may help new people to pick something to work on
> docs: mention project board in CONTRIBUTING.md

- README.md
As requested in https://t.me/grammyjs/103854
> docs: add `"grammy/web"` note to README

- README.md
> docs: update API ref link in README

- package.json
- src/convenience/keyboard.ts
- src/filter.ts
- src/platform.deno.ts
- src/platform.web.ts
- src/types.deno.ts
- src/types.web.ts
- test/bot.test.ts
- test/composer.test.ts
- test/context.test.ts
- test/convenience/keyboard.test.ts
- test/convenience/session.test.ts
- test/filter.test.ts
https://core.telegram.org/bots/api#february-3-2023
> feat: support Bot API 6.5

- src/convenience/frameworks.ts
> refactor: share resp generation code between framework adapters

- package.json
- src/core/api.ts
- src/types.deno.ts
- src/types.web.ts
As reported in https://t.me/grammyjs/118620
> fix: type of createNewStickerSet > stickers is an array

- package.json
- src/platform.deno.ts
- src/types.deno.ts
- src/types.node.ts
- test/bot.test.ts
- test/composer.d.test.ts
- test/composer.test.ts
- test/context.test.ts
- test/convenience/keyboard.test.ts
- test/convenience/session.test.ts
- test/core/client.test.ts
- test/core/error.test.ts
- test/core/payload.test.ts
- test/deps.test.ts
- test/filter.test.ts
- test/types.test.ts
Improves the test setup and add test for most of `InputFile`.
> test: refactor and extend tests

- src/context.ts
We trust https://t.me/grammyjs/123017
> feat: narrow down ctx.from inside private chats

- src/context.ts
https://github.com/grammyjs/emoji/pull/19#discussion_r1239375175
> refactor: use never record type instead of empty object

- CODE_OF_CONDUCT.md
https://github.com/grammyjs/grammY/blob/new-guidelines/CODE_OF_CONDUCT.md#guidelines
> Fix admin guidelines in CODE_OF_CONDUCT.md

- CODE_OF_CONDUCT.md
Adding extra info that any report can be done over Telegram. Also from sources outside of telegram.
> docs: clarify CoC

- src/bot.ts
> docs: fix typo

- package.json
- src/context.ts
- src/core/api.ts
- src/filter.ts
- src/types.deno.ts
- src/types.web.ts
https://core.telegram.org/bots/api#august-18-2023
> feat: update to Bot API 6.8

- src/platform.deno.ts
- src/platform.web.ts
- src/types.deno.ts
- src/types.web.ts
> refactor: reduce Deno deps

- package.json
- src/platform.deno.ts
- src/platform.web.ts
- src/types.deno.ts
- src/types.web.ts
Updates all deps including the Bot API types
> build: update deps

- src/convenience/frameworks.ts
Closes #547 
Tested with `oak@14`
> fix: oak body json

- src/convenience/frameworks.ts
> fix: set content-type for fastify

- src/context.ts
- src/convenience/session.ts
- src/filter.ts
- test/context.test.ts
- test/convenience/session.test.ts
As requested in https://t.me/grammyjs/229384
> feat: add ctx.chatId

- src/bot.ts
- src/core/error.ts
> feat: add warnings for errors 401 and 409

- src/filter.ts
> fix: type of ctx.editedMessage

- src/bot.ts
> fix: do not crash bot.stop if starting failed

- src/context.ts
- src/core/api.ts
> fix: add options bag to setChatPermissions

- README.md
- package.json
- src/filter.ts
- src/types.deno.ts
- src/types.web.ts
https://core.telegram.org/bots/api#july-7-2024
> feat: support Bot API 7.7

- README.md
- package.json
- src/types.deno.ts
- src/types.web.ts
https://core.telegram.org/bots/api#july-31-2024
> feat: support Bot API 7.8

- test/context.test.ts
> fix: drop lost testing output

- README.md
- package.json
- src/context.ts
- src/core/api.ts
- src/filter.ts
- src/types.deno.ts
- src/types.web.ts
- test/context.test.ts
https://core.telegram.org/bots/api#august-14-2024
> feat: support Bot API 7.9

- package.json
- src/context.ts
- src/filter.ts
- src/types.deno.ts
- src/types.web.ts
https://core.telegram.org/bots/api#september-6-2024
> feat: support Bot API 7.10

- .github/workflows/deno.yml
- .github/workflows/release.yml
- .github/workflows/third_party.yml
- deno.jsonc
- test/convenience/webhook.test.ts
- test/core/client.test.ts
Updates CI to Deno 2, and updates the checkout action to v4. Makes tests compatible with Deno 2.
> chore: update deps inside CI config

- src/bot.ts
As reported in https://t.me/grammyjs/276875
> docs: update PollingOptions.allowed_updates

- README.md
- package.json
- src/context.ts
- src/convenience/keyboard.ts
- src/core/api.ts
- src/types.deno.ts
- src/types.web.ts
https://core.telegram.org/bots/api#october-31-2024
> feat: support Bot API 7.11

- src/core/client.ts
Improved `fetch` handling in `ApiClient` to ensure compatibility with Cloudflare workers by calling `fetch` without context
Closed #659
> fix: implement custom fetch handling in ApiClient for Cloudflare compatibility

- README.md
- package.json
- src/context.ts
- src/core/api.ts
- src/types.deno.ts
- src/types.web.ts
https://core.telegram.org/bots/api#november-17-2024
> feat: support Bot API 8.0

- .all-contributorsrc
- README.md
For their contribution in https://github.com/grammyjs/website/pull/1156
> docs: add mahovich as a contributor for doc

- README.md
- package.json
- src/types.deno.ts
- src/types.web.ts
https://core.telegram.org/bots/api#december-4-2024
> feat: support Bot API 8.1

- src/convenience/frameworks.ts
As mentioned in https://github.com/grammyjs/grammY/issues/737#issuecomment-2593526070
> type: fix Azure Function v3 Adapter Context Type

- src/context.ts
- src/filter.ts
- test/composer.type.test.ts
- test/context.test.ts
- test/deps.test.ts
- test/filter.test.ts
> feat: add `ctx.txt`

- .github/workflows/deno.yml
> chore(ci): run on PQs from forks

- src/core/client.ts
https://core.telegram.org/bots/api#getavailablegifts
> fix: add getAvailableGifts as zero param method

- src/convenience/frameworks.ts
- test/convenience/webhook.test.ts
Hello. Here's an adapter for Elysia web server.
Also to easier type hook arguments I added elysia as optional peer dependency, so that could perhaps be utilized for other adapters to make the code more compact and up-to-date
> feat(convenience): elysia webhook adapter

- src/context.ts
Closes #619
Closes #759 by superseding it
> fix: distribute chat type context types

- src/context.ts
- src/core/api.ts
Closes https://github.com/grammyjs/website/pull/1201
> fix: add missing business connection identifiers in some places

- src/bot.ts
- src/context.ts
- src/convenience/keyboard.ts
- src/core/api.ts
- test/bot.test.ts
- test/filter.test.ts
I noticed a typo in a TSDoc, thought I might fix along with any other I stumbled across using a code spell checker.
> Fix a few typos

- README.md
- deno.jsonc
- package.json
- src/context.ts
- src/core/api.ts
- src/core/client.ts
- src/filter.ts
- src/types.deno.ts
- src/types.web.ts
https://core.telegram.org/bots/api#july-3-2025
> feat: support Bot API 9.1

- README.md
Removed mention of GrammY's presence on Twitter.
Account deleted/banned.
<details>
<summary>screenshots</summary>
</details>
> docs: remove Twitter link from README.md

- README.md
- package.json
- src/context.ts
- src/core/api.ts
- src/filter.ts
- src/types.deno.ts
- src/types.web.ts
https://core.telegram.org/bots/api#august-15-2025
> feat: support Bot API 9.2

- src/convenience/frameworks.ts
> fix: properly end fastify requests

- bundling/bundle-web.ts
- src/convenience/frameworks.ts
- src/platform.deno.ts
- src/platform.web.ts
- src/types.deno.ts
- src/types.web.ts
- test/convenience/webhook.test.ts
They seem to have updated their type definitions, so we need to follow along
> fix: update elysia types

- src/bot.ts
- src/composer.ts
- src/core/client.ts
- src/types.ts
> docs: fix bad usages of @
